### ISSUE TITLE
OnBeforeTransition - promise returning false doesn't cancel state transition

### ISSUE THREAD

**Issue by adrianhara** [taoqf/javascript-state-machine#1]
According to the docs, the following behavior is incorrect: when the `onBeforeTransition` function returns a `Promise` which resolves with `false`, I would expect that the state transition fails. However that's not the case, it continues and calls `onEnterState`.

What I noticed is that:
a. If the `onBeforeTransition` method is sync and returns `false` synchronously, then it behaves as expected and the state transition is canceled.
b. If the `onBeforeTransition` method is async and returns a rejected promise, then it also behaves as expected and the state transition is canceled.

Are the docs incorrect maybe? Or is it a bug?

**Comment by taoqf** [comment]
I do not think this is a bug, I think
```ts
return false;
```
is equal to
```ts
return new Promise((resolve, reject)=>{
reject();
});
```
