### ISSUE TITLE
Not all constituents are callable

### ISSUE THREAD

**Issue by maciejmiara** [taoqf/javascript-state-machine#11]
In Typescript 4.1, following line causes an issue
https://github.com/taoqf/javascript-state-machine/blob/master/types/state-machine.d.ts#L5

When calling from code `stateMachine[transition]()`, following error is returned by TS
"Not all constituents of type 'string | string[] | ((...args: any[]) => any)' are callable.
    Type 'string' has no call signatures."

**Comment by taoqf** [comment]
try 3.1.6

**Comment by maciejmiara** [comment]
Thanks a lot!
