### ISSUE TITLE
Typescript Definition files error

### ISSUE THREAD

**Issue by demisx** [taoqf/javascript-state-machine#3]
Hi. I've installed this module under existing TypeScript project, because the upstream one still doesn't have v3 type definitions as far as I understand. However, the `types/state-machine.d.ts` is throwing a bunch of errors in my VSCode IDE (see attached). Am I missing anything?

![screen shot 2018-08-02 at 9 28 32 am](https://user-images.githubusercontent.com/4452412/43597385-c05daa4e-9636-11e8-8b56-cd73844ab7d0.gif)

**Comment by taoqf** [comment]
pls try the latest version

**Comment by demisx** [comment]
Indeed, the errors are gone now. Thank you!
