### ISSUE TITLE
ReferenceError: dist is not defined

### ISSUE THREAD

**Issue by devzsolt** [taoqf/javascript-state-machine#6]
Something looks bad in the minified script which is the entry point of the lib.

![image](https://user-images.githubusercontent.com/6530545/44623480-da877b80-a88c-11e8-9b1c-6c5b1c25bdd3.png)

I'm using
"react-app-rewired": "^1.5.2",
"react-scripts-ts": "^2.17.0",
webpack "3.8.1"

The problem occures with dev server and production build as well. Do you have any idea what's wrong?
I suspect that setting the main to `"dist/state-machine.min.js"` might not be a good idea, the original lib has `"lib/state-machine.js"`. Perhaps the double uglification causes a mess. What do you think?

**Comment by taoqf** [comment]
Indeed, I will take a look.

**Comment by taoqf** [comment]
[3.1.3](https://www.npmjs.com/package/@taoqf/javascript-state-machine) is released.
Thank you.

**Comment by devzsolt** [comment]
Works like a charm, thanks for the quick help!
